var libchat_inline = {
   iid: "59",
   key: "fb10446730e271c",
   domain: "libanswers.mit.edu",
   color_heading: "#004CBD",
   splash: "Chat with us",
   input_name: "Kerberos username:",
   input_dept: "",
   wait: "Please wait... Someone will be with you shortly!",
   ops_left: "Thanks for your question!<br /><br />If you have a few moments, it would be helpful if you could answer 3 questions to help us improve this chat service. <a href=\"http://libguides.mit.edu/survey.php?survey_id=8007\" target=\"_blank\">Fill out survey.</a>",
   trans_prompt: "Email address to send this chat transcript to:",
   error_offline: "Sorry it doesn't appear that anyone is online... Please try again later.",
   width: "180px",
   height: "300px",
   offline: "Chat with us",
   star_ratings: false,
   file_upload: false,
   la_hide: true,
   la_hide_msg: "Chat service is usually available M-F 12-5.<br /><br />In the meantime, <a href=\"http://libraries-dev.mit.edu/ask-email\">fill out our form</a>, and we'll get back to you! [MIT only]",
   depart_id: "719"
};