name: Build stylesheets
on:
  pull_request:
    branches: [ main ]
jobs:
  compile_sass:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout theme
        uses: actions/checkout@v2
      - name: Compile global
        uses: gha-utilities/sass-build@v0.2.2
        with:
          source: css/global.scss
          destination: css/build/global.css
      - name: Compile forms
        uses: gha-utilities/sass-build@v0.2.2
        with:
          source: css/forms.scss
          destination: css/build/forms.css
      - name: Compile hours
        uses: gha-utilities/sass-build@v0.2.2
        with:
          source: css/hours.scss
          destination: css/build/hours.css
